name: app_submission_flutter_fundamental
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  http: ^0.13.5
  connectivity_plus: ^3.0.3
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  sqflite: ^2.2.6
  path: ^1.8.2
  shared_preferences: ^2.0.20
  intl: ^0.18.0
  flutter_local_notifications: ^13.0.0
  android_alarm_manager_plus: ^2.1.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/